meta:
    name: Convolution pipeline
    author: JT
    version: 1.0
    description: This pipeline runs HIP 

config:
    error: MC
    iterations: 10

data:
    body: NGC4254
    geometry:
        distance: 36
        redshift: 0.00803

    #body: NGC6946
    #geometry:
    #    distance: 7
    #    redshift: 0.000133

    bands:
        - input: inputs/NGC4254/NGC4254_MIPS1.fits
          #error: inputs/NGC4254/NGC4254_MIPS1_Error.fits
          calError: 5.4
          name: MIPS1

before:
  - step: hip.foreground
    parameters:
      factor: 3
      raTrim: 5
      decTrim: 5

pipeline: 
    - step: hip.cutout
      parameters:
        raTrim: 10
        decTrim: 10

    - step: hip.background
      parameters:
        cellSize: 4

    - step: hip.convolution
      parameters:
          kernel: kernels/Kernel_LowRes_PACS1_to_SPIRE3.fits
   
    - step: hip.reproject
      parameters:
          target: inputs/NGC4254/NGC4254_SPIRE3.fits
    
after:
    - step: util.integrate
      parameters:
          radius: 2
