meta:
    name: Convolution pipeline
    author: JT
    version: 1.0
    description: This pipeline runs HIP 

config:
    error: MC
    iterations: 1

data:
    body: NGC4254
    geometry:
        ra: 184.70655
        dec: 14.41641
        distance: 36
        inclination: 20.1
        positionAngle: -35.745
        majorAxis: 210
        axialRatio: 1.3471
        radius: 5.01
        redshift: 0.00803

    #body: NGC6946
    #geometry:
    #    ra: 308.71905
    #    dec: 60.15361
    #    distance: 7
    #    inclination: 18.3
    #    positionAngle: 0
    #    majorAxis: 207
    #    axialRatio: 1.09205367645
    #    radius: 11.4815347
    #    redshift: 0.000133

    bands:
        - input: inputs/NGC4254/NGC4254_MIPS3.fits
          error: inputs/NGC4254/NGC4254_MIPS3_Error.fits
          calError: 5.4
          name: MIPS3

before:
  - step: hip.cutout
    parameters:
      raTrim: 10
      decTrim: 10

  #- step: hip.foreground
  #  parameters:
  #    factor: 3
  #    raTrim: 10
  #    decTrim: 10

pipeline: 
    - step: hip.background
      parameters:
        cellSize: 4

    - step: hip.convolution
      parameters:
          kernel: kernels/Kernel_LowRes_PACS1_to_SPIRE3.fits
   
    - step: hip.reproject
      parameters:
        target: inputs/NGC4254/NGC4254_SPIRE3.fits
    
after:
    - step: util.integrate
      parameters:
          radius: 2
  
