meta:
    name: Convolution pipeline
    author: JT
    version: 1.0
    description: This pipeline runs HIP 

config:
    parallel: No
    error: MC

data:
    body: NGC4254
    geometry:
        ra: 184.70655
        dec: 14.41641
        distance: 36
        inclination: 20.1
        positionAngle: -35.745
        majorAxis: 210
        axialRatio: 1.3471
        radius: 5.01
        redshift: 0.00803
    bands:
        - input: inputs/NGC4254_SPIRE2.fits
          #error: inputs/NGC4254_SPIRE2_Error.fits
          name: SPIRE2
          calError: 5.0

pipeline:
    - step: hip.cutout
      parameters:
          raTrim: 15
          decTrim: 15

    - step: hip.background
      parameters:
          cellSize: 10

    - step: hip.convolution
      parameters:
          name: SPIRE3
          kernel: kernels/Kernel_LowRes_SPIRE_350_to_SPIRE_500.fits

    - step: hip.reproject
      parameters:
          target: inputs/NGC4254_SPIRE3.fits
    
    - step: hip.integrate
    
    - step: hip.plot
